#!/usr/bin/env python3
"""
HTML to C Header Converter with Embedded Binary Support
Converts HTML files to include/html_index.h format with embedded binary data.

This script is specifically designed for converting HTML pages (of any size)
with dynamic timestamp support for anti-detection purposes.

Usage:
    python3 tools/HTML2TimeStampH.py <input.html>
    python3 tools/HTML2TimeStampH.py config-files/index.html

The output creates an embedded binary version of the HTML that:
- Supports files of ANY size (no ISO C99 string length limits)
- Preserves %s timestamp placeholders for dynamic injection
- Can be used with sprintf() for runtime timestamp replacement
"""

import sys
import os
import subprocess
from pathlib import Path
from datetime import datetime

def html_to_c_header_embedded(html_content, title="Index Page"):
    """Convert HTML content to C header with embedded binary data"""

    # Convert to bytes
    html_bytes = html_content.encode('utf-8')

    # Generate hex representation in C format (like xxd -i)
    hex_lines = []
    bytes_per_line = 16

    for i in range(0, len(html_bytes), bytes_per_line):
        chunk = html_bytes[i:i + bytes_per_line]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        hex_lines.append(f"  {hex_bytes},")

    # Remove trailing comma from last line
    if hex_lines:
        hex_lines[-1] = hex_lines[-1].rstrip(',')

    hex_data = '\n'.join(hex_lines)

    # Generate the complete header (compatible with response.c)
    header = f"""/* Aviontex {title} - Auto-generated from HTML
 *
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * This file is auto-generated by tools/HTML2TimeStampH.py
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Instead, edit the source HTML and regenerate using:
 *   python3 tools/HTML2TimeStampH.py config-files/index.html
 *
 * TIMESTAMP SUPPORT:
 *   This file includes embedded binary HTML with %s placeholders for dynamic injection.
 *   At runtime, replace %s with current timestamp using snprintf():
 *
 *   Example C code:
 *   {{
 *       char response[16384];
 *       char timestamp[256];
 *       time_t now = time(NULL);
 *       snprintf(timestamp, sizeof(timestamp), "%s", ctime(&now));
 *       snprintf(response, sizeof(response), (const char*)index_html, timestamp);
 *   }}
 *
 * Format:
 *   - Binary embedded HTML (no string literal length limits)
 *   - NULL-terminated for C string operations
 *   - Supports files of any size (tested with 200KB+)
 *   - index_html_len is byte count (excluding NULL terminator)
 *
 * Features:
 *   - Responsive design (mobile-friendly)
 *   - Modern animations and effects
 *   - Professional branding
 *   - Anti-detection via dynamic timestamps
 */

#ifndef INCLUDE_HTML_INDEX_H
#define INCLUDE_HTML_INDEX_H

unsigned char index_html[] = {{
{hex_data}
}};

unsigned int index_html_len = {len(html_bytes)};  /* Exclude NULL terminator */

#endif /* INCLUDE_HTML_INDEX_H */
"""

    return header


def convert_html_to_header(input_html_path):
    """Convert HTML file to html_index.h"""

    input_path = Path(input_html_path)

    # Validate input file
    if not input_path.exists():
        print(f"❌ ERROR: Input file not found: {input_html_path}", file=sys.stderr)
        return False

    if not input_path.is_file():
        print(f"❌ ERROR: Not a file: {input_html_path}", file=sys.stderr)
        return False

    # Read HTML content
    try:
        with open(input_path, 'r', encoding='utf-8') as f:
            html_content = f.read()
    except Exception as e:
        print(f"❌ ERROR: Failed to read HTML file: {e}", file=sys.stderr)
        return False

    # Determine title from filename
    title = input_path.stem.replace('_', ' ').title()

    # Convert to C header
    c_header = html_to_c_header_embedded(html_content, title)
    if not c_header:
        return False

    # Write to include/html_index.h
    output_path = Path("include/html_index.h")
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(c_header)

        input_size = len(html_content)
        output_size = len(c_header)

        # Print success message with details
        print(f"\n✅ Conversion successful!", file=sys.stderr)
        print(f"   Input:    {input_path} ({input_size:,} bytes)", file=sys.stderr)
        print(f"   Output:   {output_path} ({output_size:,} bytes)", file=sys.stderr)
        print(f"   Title:    {title}", file=sys.stderr)
        print(f"   Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", file=sys.stderr)

        # Check for timestamp placeholders
        if '%s' in html_content:
            count = html_content.count('%s')
            print(f"   Timestamps: ✓ {count} placeholder(s) found and preserved", file=sys.stderr)
        else:
            print(f"   Timestamps: ⚠ No %s placeholders found in HTML", file=sys.stderr)

        print(f"\n🚀 Ready to use! Include it in your C code:", file=sys.stderr)
        print(f"   #include \"include/html_index.h\"", file=sys.stderr)
        print(f"\n💡 To replace timestamps at runtime, use snprintf():", file=sys.stderr)
        print(f"   char response[16384]; snprintf(response, sizeof(response), (const char*)index_html, timestamp);", file=sys.stderr)
        print(f"   (No string literal length limits - supports files of any size!)", file=sys.stderr)

        return True

    except Exception as e:
        print(f"❌ ERROR: Failed to write output file: {e}", file=sys.stderr)
        return False


def main():
    """Main entry point"""

    # Check arguments
    if len(sys.argv) < 2 or sys.argv[1] in ['-h', '--help', '?']:
        print(__doc__)
        sys.exit(0 if sys.argv[1:] else 1)

    input_file = sys.argv[1]

    # Convert HTML to header
    success = convert_html_to_header(input_file)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
