#!/usr/bin/env python3
"""
HTML to C Header Converter
Converts HTML files to include/html_index.h format

Usage:
    python3 tools/html_to_header.py <input.html> [output.h]

Examples:
    python3 tools/html_to_header.py index.html
    python3 tools/html_to_header.py landing.html include/html_index.h
    python3 tools/html_to_header.py - < index.html  # Read from stdin
"""

import sys
import os
from pathlib import Path
from datetime import datetime

def html_to_c_string(html_content, title="Index Page"):
    """Convert HTML content to C header format"""

    # Escape backslashes and quotes
    c_string = html_content.replace('\\', '\\\\').replace('"', '\\"')

    # Split into lines for processing
    lines = c_string.split('\n')

    # Generate C array
    c_array = []
    for line in lines:
        c_array.append('\t"' + line + '\\n"')

    # Remove trailing \n from last line
    if c_array:
        c_array[-1] = c_array[-1][:-4] + '"'  # Remove last \n"

    # Build content string
    lines_content = '\n'.join(c_array)

    # Build complete header
    header = f"""/* Aviontex {title} - Auto-generated from HTML
 *
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * This file is auto-generated by tools/html_to_header.py
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Instead, edit the source HTML and regenerate using:
 *   python3 tools/html_to_header.py source.html
 *
 * Features:
 *   - Responsive design (mobile-friendly)
 *   - Modern animations and effects
 *   - Professional branding
 */

#ifndef INCLUDE_HTML_INDEX_H
#define INCLUDE_HTML_INDEX_H

unsigned char index_html[] =
{lines_content}
;

unsigned int index_html_len = sizeof(index_html) - 1;  /* Exclude NULL terminator */

#endif /* INCLUDE_HTML_INDEX_H */
"""

    return header

def convert_file(input_file, output_file=None, title="Index Page"):
    """Convert HTML file to C header"""

    # Read input
    if input_file == '-':
        print("Reading from stdin...", file=sys.stderr)
        html_content = sys.stdin.read()
        input_path = None
    else:
        input_path = Path(input_file)
        if not input_path.exists():
            print(f"ERROR: Input file not found: {input_file}", file=sys.stderr)
            return False

        with open(input_path, 'r', encoding='utf-8') as f:
            html_content = f.read()

    # Determine output file
    if output_file is None:
        output_file = "include/html_index.h"

    output_path = Path(output_file)

    # Convert
    try:
        c_header = html_to_c_string(html_content, title)
    except Exception as e:
        print(f"ERROR: Failed to convert HTML: {e}", file=sys.stderr)
        return False

    # Write output
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(c_header)

        file_size = len(html_content)
        print(f"✅ Converted successfully!", file=sys.stderr)
        print(f"   Input:  {input_file if input_file != '-' else 'stdin'} ({file_size} bytes)", file=sys.stderr)
        print(f"   Output: {output_path}", file=sys.stderr)
        print(f"   Size:   {len(c_header)} bytes (C header)", file=sys.stderr)

        return True

    except Exception as e:
        print(f"ERROR: Failed to write output file: {e}", file=sys.stderr)
        return False

def main():
    """Main entry point"""

    if len(sys.argv) < 2 or sys.argv[1] in ['-h', '--help']:
        print(__doc__)
        sys.exit(0 if sys.argv[1:] else 1)

    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    # Determine title from filename
    if input_file != '-':
        title = Path(input_file).stem.replace('_', ' ').title()
    else:
        title = "Index Page"

    success = convert_file(input_file, output_file, title)
    sys.exit(0 if success else 1)

if __name__ == '__main__':
    main()
