#!/bin/bash
# TLSGateNXv3 - Multi-SubCA Directory Setup
# Creates proper directory structure for RSA/ECDSA/SM2 SubCAs

set -e

# Configuration
BASE_DIR="${1:-.}"
VERBOSE="${2:-0}"

if [ "$VERBOSE" = "1" ]; then
    set -x
fi

echo "=================================================="
echo "TLSGateNXv3 - Multi-SubCA Directory Setup"
echo "=================================================="
echo ""

# Validate base directory
if [ ! -d "$BASE_DIR" ]; then
    echo "ERROR: Base directory does not exist: $BASE_DIR"
    exit 1
fi

echo "Base directory: $BASE_DIR"
echo ""

# Function to setup SubCA directory
setup_subca() {
    local subca_name=$1
    local subca_dir="$BASE_DIR/$subca_name"

    echo "Setting up $subca_name SubCA..."

    # Create directory structure
    mkdir -p "$subca_dir/certs"

    # Check for required files
    if [ ! -f "$subca_dir/root.crt" ]; then
        echo "  ⚠️  Missing: $subca_dir/root.crt (required)"
    else
        echo "  ✓ Found: root.crt"
    fi

    if [ ! -f "$subca_dir/ca.crt" ]; then
        echo "  ⚠️  Missing: $subca_dir/ca.crt (required)"
    else
        echo "  ✓ Found: ca.crt"
    fi

    if [ ! -f "$subca_dir/ca.key" ]; then
        echo "  ⚠️  Missing: $subca_dir/ca.key (required)"
    else
        echo "  ✓ Found: ca.key"
        chmod 600 "$subca_dir/ca.key"
        echo "  ✓ Set permissions: ca.key (0600)"
    fi

    # Create .index placeholder
    if [ ! -f "$subca_dir/certs/.index" ]; then
        cat > "$subca_dir/certs/.index" << 'EOF'
# Certificate Index - Generated by setup script
# domain|expiration|algorithm|days_remaining
EOF
        echo "  ✓ Created: .index file"
    fi

    # Create .gitkeep for git tracking
    touch "$subca_dir/certs/.gitkeep"

    # Set permissions
    chmod 755 "$subca_dir"
    chmod 755 "$subca_dir/certs"
    chmod 644 "$subca_dir/certs/.index"

    echo "  ✓ Setup complete for $subca_name"
    echo ""
}

# Setup all SubCAs
setup_subca "RSA"
setup_subca "ECDSA"
setup_subca "SM2"

# Verify RootCA consistency
echo "Verifying RootCA consistency..."
if [ -f "$BASE_DIR/RSA/root.crt" ] && [ -f "$BASE_DIR/ECDSA/root.crt" ] && [ -f "$BASE_DIR/SM2/root.crt" ]; then
    # Compare root certificates (rough check - must be identical)
    if cmp -s "$BASE_DIR/RSA/root.crt" "$BASE_DIR/ECDSA/root.crt" && \
       cmp -s "$BASE_DIR/ECDSA/root.crt" "$BASE_DIR/SM2/root.crt"; then
        echo "  ✓ RootCA files are identical across all SubCAs"
    else
        echo "  ⚠️  WARNING: RootCA files differ between SubCAs!"
        echo "     All SubCAs should share the SAME RootCA certificate"
    fi
else
    echo "  ⚠️  Some RootCA files missing, cannot verify consistency"
fi

echo ""
echo "=================================================="
echo "Directory Structure:"
echo "=================================================="
tree -L 2 "$BASE_DIR" 2>/dev/null || find "$BASE_DIR" -maxdepth 2 -type d | sort

echo ""
echo "=================================================="
echo "Final Checklist:"
echo "=================================================="

# Checklist
ERRORS=0

check_file() {
    local file=$1
    local desc=$2
    if [ -f "$file" ]; then
        echo "✓ $desc"
    else
        echo "✗ $desc"
        ERRORS=$((ERRORS + 1))
    fi
}

check_dir() {
    local dir=$1
    local desc=$2
    if [ -d "$dir" ]; then
        echo "✓ $desc"
    else
        echo "✗ $desc"
        ERRORS=$((ERRORS + 1))
    fi
}

echo ""
echo "RSA SubCA:"
check_dir "$BASE_DIR/RSA" "  Directory: RSA/"
check_file "$BASE_DIR/RSA/root.crt" "  Certificate: root.crt"
check_file "$BASE_DIR/RSA/ca.crt" "  Certificate: ca.crt"
check_file "$BASE_DIR/RSA/ca.key" "  Key: ca.key"
check_dir "$BASE_DIR/RSA/certs" "  Storage: certs/"

echo ""
echo "ECDSA SubCA:"
check_dir "$BASE_DIR/ECDSA" "  Directory: ECDSA/"
check_file "$BASE_DIR/ECDSA/root.crt" "  Certificate: root.crt"
check_file "$BASE_DIR/ECDSA/ca.crt" "  Certificate: ca.crt"
check_file "$BASE_DIR/ECDSA/ca.key" "  Key: ca.key"
check_dir "$BASE_DIR/ECDSA/certs" "  Storage: certs/"

echo ""
echo "SM2 SubCA:"
check_dir "$BASE_DIR/SM2" "  Directory: SM2/"
check_file "$BASE_DIR/SM2/root.crt" "  Certificate: root.crt"
check_file "$BASE_DIR/SM2/ca.crt" "  Certificate: ca.crt"
check_file "$BASE_DIR/SM2/ca.key" "  Certificate: ca.key"
check_dir "$BASE_DIR/SM2/certs" "  Storage: certs/"

echo ""
echo "=================================================="

if [ $ERRORS -eq 0 ]; then
    echo "✅ ALL CHECKS PASSED!"
    echo "=================================================="
    echo ""
    echo "Setup is complete. You can now use TLSGateNXv3 with:"
    echo ""
    echo "  Base directory: $BASE_DIR"
    echo "  RSA SubCA:      $BASE_DIR/RSA/"
    echo "  ECDSA SubCA:    $BASE_DIR/ECDSA/"
    echo "  SM2 SubCA:      $BASE_DIR/SM2/"
    echo ""
    echo "Generated certificates will be stored in:"
    echo "  RSA:   $BASE_DIR/RSA/certs/"
    echo "  ECDSA: $BASE_DIR/ECDSA/certs/"
    echo "  SM2:   $BASE_DIR/SM2/certs/"
    echo ""
    exit 0
else
    echo "❌ SETUP INCOMPLETE"
    echo "=================================================="
    echo ""
    echo "Missing files ($ERRORS errors). Please add:"
    echo "  - root.crt in each SubCA directory (all identical)"
    echo "  - ca.crt (SubCA certificate) in each directory"
    echo "  - ca.key (SubCA private key) in each directory"
    echo ""
    exit 1
fi
